config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'
	resources :kittens 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: :true, length: { maximum: 50 },
			  format: { with: /\A[a-zA-Z]+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  
  def new
  	@kitten = Kitten.new
  end

  def create
  	@kitten = Kitten.new(kitten_params)
  	if @kitten.save
  		flash[:success] = "Kitten Created"
  		redirect_to kitten_path(@kitten.id)
  	else
  		render 'new'
  	end
  end

  def index
  	@kittens = Kitten.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kittens}
    end
  end

  def show
  	@kitten = Kitten.find(params[:id])
  	respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kitten}
    end
  end

  def edit
  	@kitten = Kitten.find(params[:id])
  end

  def update
  	@kitten = Kitten.find(params[:id])
  	if @kitten.update_attributes(kitten_params)
  		flash[:success] = "Kitten Edited"
  		redirect_to kitten_path(@kitten.id)
  	else
  		render 'edit'
  	end
  end

  def destroy
  	Kitten.find(params[:id]).destroy
  	flash[:success] = "Kitten Deleted"
    redirect_to kittens_path
  end

  private

	  def kitten_params
	  	params.require(:kitten).permit(:name, :age, :cuteness, :softness)
	  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<h1>Edit Your Kitten</h1>

<%= form_for @kitten do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.label(:name, "Name:") %>
	<%= f.text_field(:name) %> <br>
	<%= f.label(:age, "Age:") %>
	<%= f.select(:age, options_for_select(1..10)) %><br>
	<%= f.label(:cuteness, "Cuteness:") %>
	<%= f.select(:cuteness, options_for_select(1..10)) %><br>
	<%= f.label(:softness, "Softness:") %>
	<%= f.select(:softness, options_for_select(1..10)) %><br>
	<%= f.submit("Update")%> <br>
<% end %>
<li><%= link_to "Delete Kitten", kitten_path(@kitten.id),
				method: :delete, data: { confirm: "You sure?" } %></li>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>


<% @kittens.each do |kitten| %>
	<p>
		Name:
		<%= kitten.name %> <br>
		Age:
		<%= kitten.age %> <br>
		Cuteness:
		<%= kitten.cuteness %> <br>
		Softness:
		<%= kitten.softness %>
		<li><%= link_to "View Kitten", kitten_path(kitten.id) %></li>
		<li><%= link_to "Delete Kitten", kitten_path(kitten.id),
				method: :delete, data: { confirm: "You sure?" } %></li>
	</p>
<% end %>

app/views/kittens/new.html.erb
<h1>Create a New Kitten</h1>

<%= form_for @kitten do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<%= f.label(:name, "Name:") %>
	<%= f.text_field(:name) %> <br>
	<%= f.label(:age, "Age:") %>
	<%= f.select(:age, options_for_select(1..10)) %><br>
	<%= f.label(:cuteness, "Cuteness:") %>
	<%= f.select(:cuteness, options_for_select(1..10)) %><br>
	<%= f.label(:softness, "Softness:") %>
	<%= f.select(:softness, options_for_select(1..10)) %><br>
	<%= f.submit("Create")%> <br>
<% end %>

app/views/kittens/show.html.erb
<h1>Your Kitten</h1>

<p>
	Name:
	<%= @kitten.name %> <br>
	Age:
	<%= @kitten.age %> <br>
	Cuteness:
	<%= @kitten.cuteness %> <br>
	Softness:
	<%= @kitten.softness %>
</p>
<li><%= link_to "Edit Kitten", edit_kitten_path(@kitten.id) %></li>
<li><%= link_to "Delete Kitten", kitten_path(@kitten.id),
				method: :delete, data: { confirm: "You sure?" } %></li>

app/views/layouts/_header.html.erb
<header>
  <ul>
    <li><%= link_to "All Kittens", kittens_path %></li>
    <li><%= link_to "Create Kitten", new_kitten_path %></li>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header'%>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>